using System;
using System.Collections.Generic;

namespace Foragelab.Core.DataModel
{
    public partial class Fat
    {
        public long FatId { get; set; }
        public long ResultsId { get; set; }
        public decimal? FatEe { get; set; }
        public decimal? FatAh { get; set; }
        public decimal? Ffa { get; set; }
        public decimal? Tfa { get; set; }
        public decimal? C120 { get; set; }
        public decimal? C140 { get; set; }
        public decimal? C160 { get; set; }
        public decimal? C161 { get; set; }
        public decimal? C180 { get; set; }
        public decimal? C181 { get; set; }
        public decimal? C182 { get; set; }
        public decimal? C183 { get; set; }
        public decimal? OtherFa { get; set; }
        public decimal? C120Tfa { get; set; }
        public decimal? C140Tfa { get; set; }
        public decimal? C160Tfa { get; set; }
        public decimal? C161Tfa { get; set; }
        public decimal? C180Tfa { get; set; }
        public decimal? C181Tfa { get; set; }
        public decimal? C182Tfa { get; set; }
        public decimal? C183Tfa { get; set; }
        public decimal? OtherFaTfa { get; set; }
        public decimal? C100FinalSampleCalc { get; set; }
        public decimal? C120FinalSampleCalc { get; set; }
        public decimal? C140FinalSampleCalc { get; set; }
        public decimal? C141FinalSampleCalc { get; set; }
        public decimal? C150FinalSampleCalc { get; set; }
        public decimal? C160FinalSampleCalc { get; set; }
        public decimal? C161FinalSampleCalc { get; set; }
        public decimal? C162FinalSampleCalc { get; set; }
        public decimal? C163FinalSampleCalc { get; set; }
        public decimal? C164FinalSampleCalc { get; set; }
        public decimal? C170FinalSampleCalc { get; set; }
        public decimal? C171FinalSampleCalc { get; set; }
        public decimal? C180FinalSampleCalc { get; set; }
        public decimal? C181FinalSampleCalc { get; set; }
        public decimal? C181w7FinalSampleCalc { get; set; }
        public decimal? C181w9FinalSampleCalc { get; set; }
        public decimal? C182FinalSampleCalc { get; set; }
        public decimal? C182w4FinalSampleCalc { get; set; }
        public decimal? C182w6FinalSampleCalc { get; set; }
        public decimal? C183FinalSampleCalc { get; set; }
        public decimal? C183w3FinalSampleCalc { get; set; }
        public decimal? C183w6FinalSampleCalc { get; set; }
        public decimal? C184w3FinalSampleCalc { get; set; }
        public decimal? C200FinalSampleCalc { get; set; }
        public decimal? C201w7FinalSampleCalc { get; set; }
        public decimal? C201w9FinalSampleCalc { get; set; }
        public decimal? C2021114FinalSampleCalc { get; set; }
        public decimal? C202w6FinalSampleCalc { get; set; }
        public decimal? C203w3FinalSampleCalc { get; set; }
        public decimal? C203w6FinalSampleCalc { get; set; }
        public decimal? C204w3FinalSampleCalc { get; set; }
        public decimal? C204w6FinalSampleCalc { get; set; }
        public decimal? C205w3FinalSampleCalc { get; set; }
        public decimal? C215w3FinalSampleCalc { get; set; }
        public decimal? C220FinalSampleCalc { get; set; }
        public decimal? C221FinalSampleCalc { get; set; }
        public decimal? C22111FinalSampleCalc { get; set; }
        public decimal? C221w9FinalSampleCalc { get; set; }
        public decimal? C225w3FinalSampleCalc { get; set; }
        public decimal? C225w6FinalSampleCalc { get; set; }
        public decimal? C226w3FinalSampleCalc { get; set; }
        public decimal? C240FinalSampleCalc { get; set; }
        public decimal? C241FinalSampleCalc { get; set; }
        public decimal? C60FinalSampleCalc { get; set; }
        public decimal? C80FinalSampleCalc { get; set; }
        public decimal? OtherFinalSampleCalc { get; set; }
        public decimal? C100FinalRelativeCalc { get; set; }
        public decimal? C120FinalRelativeCalc { get; set; }
        public decimal? C140FinalRelativeCalc { get; set; }
        public decimal? C141FinalRelativeCalc { get; set; }
        public decimal? C150FinalRelativeCalc { get; set; }
        public decimal? C160FinalRelativeCalc { get; set; }
        public decimal? C161FinalRelativeCalc { get; set; }
        public decimal? C162FinalRelativeCalc { get; set; }
        public decimal? C163FinalRelativeCalc { get; set; }
        public decimal? C164FinalRelativeCalc { get; set; }
        public decimal? C170FinalRelativeCalc { get; set; }
        public decimal? C171FinalRelativeCalc { get; set; }
        public decimal? C180FinalRelativeCalc { get; set; }
        public decimal? C181FinalRelativeCalc { get; set; }
        public decimal? C181w7FinalRelativeCalc { get; set; }
        public decimal? C181w9FinalRelativeCalc { get; set; }
        public decimal? C182FinalRelativeCalc { get; set; }
        public decimal? C182w4FinalRelativeCalc { get; set; }
        public decimal? C182w6FinalRelativeCalc { get; set; }
        public decimal? C183FinalRelativeCalc { get; set; }
        public decimal? C183w3FinalRelativeCalc { get; set; }
        public decimal? C183w6FinalRelativeCalc { get; set; }
        public decimal? C184w3FinalRelativeCalc { get; set; }
        public decimal? C200FinalRelativeCalc { get; set; }
        public decimal? C201w7FinalRelativeCalc { get; set; }
        public decimal? C201w9FinalRelativeCalc { get; set; }
        public decimal? C2021114FinalRelativeCalc { get; set; }
        public decimal? C202w6FinalRelativeCalc { get; set; }
        public decimal? C203w3FinalRelativeCalc { get; set; }
        public decimal? C203w6FinalRelativeCalc { get; set; }
        public decimal? C204w3FinalRelativeCalc { get; set; }
        public decimal? C204w6FinalRelativeCalc { get; set; }
        public decimal? C205w3FinalRelativeCalc { get; set; }
        public decimal? C215w3FinalRelativeCalc { get; set; }
        public decimal? C220FinalRelativeCalc { get; set; }
        public decimal? C221FinalRelativeCalc { get; set; }
        public decimal? C22111FinalRelativeCalc { get; set; }
        public decimal? C221w9FinalRelativeCalc { get; set; }
        public decimal? C225w3FinalRelativeCalc { get; set; }
        public decimal? C225w6FinalRelativeCalc { get; set; }
        public decimal? C226w3FinalRelativeCalc { get; set; }
        public decimal? C240FinalRelativeCalc { get; set; }
        public decimal? C241FinalRelativeCalc { get; set; }
        public decimal? C60FinalRelativeCalc { get; set; }
        public decimal? C80FinalRelativeCalc { get; set; }
        public decimal? OtherFinalRelativeCalc { get; set; }
    }
}
