using System;
using System.Collections.Generic;

namespace Foragelab.Core.DataModel
{
    public partial class IFattyacid
    {
        public long IfattyAcidId { get; set; }
        public decimal? Batch { get; set; }
        public decimal? Code { get; set; }
        public bool? NjfHygroAdjust { get; set; }
        public bool? AdjustByHygro { get; set; }
        public bool? Release { get; set; }
        public decimal? C100calcRaw1 { get; set; }
        public decimal? C100relativeRaw1 { get; set; }
        public decimal? C100sampleRaw1 { get; set; }
        public decimal? C120calcRaw1 { get; set; }
        public decimal? C120relativeRaw1 { get; set; }
        public decimal? C120sampleRaw1 { get; set; }
        public decimal? C140calcRaw1 { get; set; }
        public decimal? C140relativeRaw1 { get; set; }
        public decimal? C140sampleRaw1 { get; set; }
        public decimal? C141calcRaw1 { get; set; }
        public decimal? C141relativeRaw1 { get; set; }
        public decimal? C141sampleRaw1 { get; set; }
        public decimal? C150calcRaw1 { get; set; }
        public decimal? C150relativeRaw1 { get; set; }
        public decimal? C150sampleRaw1 { get; set; }
        public decimal? C160calcRaw1 { get; set; }
        public decimal? C160relativeRaw1 { get; set; }
        public decimal? C160sampleRaw1 { get; set; }
        public decimal? C161calcRaw1 { get; set; }
        public decimal? C161relativeRaw1 { get; set; }
        public decimal? C161sampleRaw1 { get; set; }
        public decimal? C162calcRaw1 { get; set; }
        public decimal? C162relativeRaw1 { get; set; }
        public decimal? C162sampleRaw1 { get; set; }
        public decimal? C163calcRaw1 { get; set; }
        public decimal? C163relativeRaw1 { get; set; }
        public decimal? C163sampleRaw1 { get; set; }
        public decimal? C164calcRaw1 { get; set; }
        public decimal? C164relativeRaw1 { get; set; }
        public decimal? C164sampleRaw1 { get; set; }
        public decimal? C170calcRaw1 { get; set; }
        public decimal? C170relativeRaw1 { get; set; }
        public decimal? C170sampleRaw1 { get; set; }
        public decimal? C180calcRaw1 { get; set; }
        public decimal? C180relativeRaw1 { get; set; }
        public decimal? C180sampleRaw1 { get; set; }
        public decimal? C181w7CalcRaw1 { get; set; }
        public decimal? C181w7RelativeRaw1 { get; set; }
        public decimal? C181w7SampleRaw1 { get; set; }
        public decimal? C181w9CalcRaw1 { get; set; }
        public decimal? C181w9RelativeRaw1 { get; set; }
        public decimal? C181w9SampleRaw1 { get; set; }
        public decimal? C182w4CalcRaw1 { get; set; }
        public decimal? C182w4RelativeRaw1 { get; set; }
        public decimal? C182w4SampleRaw1 { get; set; }
        public decimal? C182w6CalcRaw1 { get; set; }
        public decimal? C182w6RelativeRaw1 { get; set; }
        public decimal? C182w6SampleRaw1 { get; set; }
        public decimal? C183w3CalcRaw1 { get; set; }
        public decimal? C183w3RelativeRaw1 { get; set; }
        public decimal? C183w3SampleRaw1 { get; set; }
        public decimal? C183w6CalcRaw1 { get; set; }
        public decimal? C183w6RelativeRaw1 { get; set; }
        public decimal? C183w6SampleRaw1 { get; set; }
        public decimal? C184w3CalcRaw1 { get; set; }
        public decimal? C184w3RelativeRaw1 { get; set; }
        public decimal? C184w3SampleRaw1 { get; set; }
        public decimal? C200calcRaw1 { get; set; }
        public decimal? C200relativeRaw1 { get; set; }
        public decimal? C200sampleRaw1 { get; set; }
        public decimal? C201w7CalcRaw1 { get; set; }
        public decimal? C201w7RelativeRaw1 { get; set; }
        public decimal? C201w7SampleRaw1 { get; set; }
        public decimal? C201w9CalcRaw1 { get; set; }
        public decimal? C201w9RelativeRaw1 { get; set; }
        public decimal? C201w9SampleRaw1 { get; set; }
        public decimal? C202w6CalcRaw1 { get; set; }
        public decimal? C202w6RelativeRaw1 { get; set; }
        public decimal? C202w6SampleRaw1 { get; set; }
        public decimal? C203w3CalcRaw1 { get; set; }
        public decimal? C203w3RelativeRaw1 { get; set; }
        public decimal? C203w3SampleRaw1 { get; set; }
        public decimal? C203w6CalcRaw1 { get; set; }
        public decimal? C203w6RelativeRaw1 { get; set; }
        public decimal? C203w6SampleRaw1 { get; set; }
        public decimal? C204w3CalcRaw1 { get; set; }
        public decimal? C204w3RelativeRaw1 { get; set; }
        public decimal? C204w3SampleRaw1 { get; set; }
        public decimal? C204w6CalcRaw1 { get; set; }
        public decimal? C204w6RelativeRaw1 { get; set; }
        public decimal? C204w6SampleRaw1 { get; set; }
        public decimal? C205w3CalcRaw1 { get; set; }
        public decimal? C205w3RelativeRaw1 { get; set; }
        public decimal? C205w3SampleRaw1 { get; set; }
        public decimal? C215w3CalcRaw1 { get; set; }
        public decimal? C215w3RelativeRaw1 { get; set; }
        public decimal? C215w3SampleRaw1 { get; set; }
        public decimal? C220calcRaw1 { get; set; }
        public decimal? C220relativeRaw1 { get; set; }
        public decimal? C220sampleRaw1 { get; set; }
        public decimal? C221w9CalcRaw1 { get; set; }
        public decimal? C221w9RelativeRaw1 { get; set; }
        public decimal? C221w9SampleRaw1 { get; set; }
        public decimal? C225w3CalcRaw1 { get; set; }
        public decimal? C225w3RelativeRaw1 { get; set; }
        public decimal? C225w3SampleRaw1 { get; set; }
        public decimal? C225w6CalcRaw1 { get; set; }
        public decimal? C225w6RelativeRaw1 { get; set; }
        public decimal? C225w6SampleRaw1 { get; set; }
        public decimal? C226w3CalcRaw1 { get; set; }
        public decimal? C226w3RelativeRaw1 { get; set; }
        public decimal? C226w3SampleRaw1 { get; set; }
        public decimal? C60calcRaw1 { get; set; }
        public decimal? C60relativeRaw1 { get; set; }
        public decimal? C60sampleRaw1 { get; set; }
        public decimal? C80calcRaw1 { get; set; }
        public decimal? C80relativeRaw1 { get; set; }
        public decimal? C80sampleRaw1 { get; set; }
        public decimal? OtherCalcRaw1 { get; set; }
        public decimal? OtherRelativeRaw1 { get; set; }
        public decimal? OtherSampleRaw1 { get; set; }
        public decimal? C181calcRaw1 { get; set; }
        public decimal? C181relativeRaw1 { get; set; }
        public decimal? C181sampleRaw1 { get; set; }
        public decimal? C182calcRaw1 { get; set; }
        public decimal? C182relativeRaw1 { get; set; }
        public decimal? C182sampleRaw1 { get; set; }
        public decimal? C183calcRaw1 { get; set; }
        public decimal? C183relativeRaw1 { get; set; }
        public decimal? C183sampleRaw1 { get; set; }
        public decimal? C20111calcRaw1 { get; set; }
        public decimal? C20111relativeRaw1 { get; set; }
        public decimal? C20111sampleRaw1 { get; set; }
        public decimal? C2021114calcRaw1 { get; set; }
        public decimal? C2021114relativeRaw1 { get; set; }
        public decimal? C2021114sampleRaw1 { get; set; }
        public decimal? C221calcRaw1 { get; set; }
        public decimal? C221relativeRaw1 { get; set; }
        public decimal? C221sampleRaw1 { get; set; }
        public decimal? C240calcRaw1 { get; set; }
        public decimal? C240relativeRaw1 { get; set; }
        public decimal? C240sampleRaw1 { get; set; }
        public decimal? C241calcRaw1 { get; set; }
        public decimal? C241relativeRaw1 { get; set; }
        public decimal? C241sampleRaw1 { get; set; }
        public decimal? C100calcRaw2 { get; set; }
        public decimal? C100relativeRaw2 { get; set; }
        public decimal? C100sampleRaw2 { get; set; }
        public decimal? C120calcRaw2 { get; set; }
        public decimal? C120relativeRaw2 { get; set; }
        public decimal? C120sampleRaw2 { get; set; }
        public decimal? C140calcRaw2 { get; set; }
        public decimal? C140relativeRaw2 { get; set; }
        public decimal? C140sampleRaw2 { get; set; }
        public decimal? C141calcRaw2 { get; set; }
        public decimal? C141relativeRaw2 { get; set; }
        public decimal? C141sampleRaw2 { get; set; }
        public decimal? C150calcRaw2 { get; set; }
        public decimal? C150relativeRaw2 { get; set; }
        public decimal? C150sampleRaw2 { get; set; }
        public decimal? C160calcRaw2 { get; set; }
        public decimal? C160relativeRaw2 { get; set; }
        public decimal? C160sampleRaw2 { get; set; }
        public decimal? C161calcRaw2 { get; set; }
        public decimal? C161relativeRaw2 { get; set; }
        public decimal? C161sampleRaw2 { get; set; }
        public decimal? C162calcRaw2 { get; set; }
        public decimal? C162relativeRaw2 { get; set; }
        public decimal? C162sampleRaw2 { get; set; }
        public decimal? C163calcRaw2 { get; set; }
        public decimal? C163relativeRaw2 { get; set; }
        public decimal? C163sampleRaw2 { get; set; }
        public decimal? C164calcRaw2 { get; set; }
        public decimal? C164relativeRaw2 { get; set; }
        public decimal? C164sampleRaw2 { get; set; }
        public decimal? C170calcRaw2 { get; set; }
        public decimal? C170relativeRaw2 { get; set; }
        public decimal? C170sampleRaw2 { get; set; }
        public decimal? C180calcRaw2 { get; set; }
        public decimal? C180relativeRaw2 { get; set; }
        public decimal? C180sampleRaw2 { get; set; }
        public decimal? C181w7CalcRaw2 { get; set; }
        public decimal? C181w7RelativeRaw2 { get; set; }
        public decimal? C181w7SampleRaw2 { get; set; }
        public decimal? C181w9CalcRaw2 { get; set; }
        public decimal? C181w9RelativeRaw2 { get; set; }
        public decimal? C181w9SampleRaw2 { get; set; }
        public decimal? C182w4CalcRaw2 { get; set; }
        public decimal? C182w4RelativeRaw2 { get; set; }
        public decimal? C182w4SampleRaw2 { get; set; }
        public decimal? C182w6CalcRaw2 { get; set; }
        public decimal? C182w6RelativeRaw2 { get; set; }
        public decimal? C182w6SampleRaw2 { get; set; }
        public decimal? C183w3CalcRaw2 { get; set; }
        public decimal? C183w3RelativeRaw2 { get; set; }
        public decimal? C183w3SampleRaw2 { get; set; }
        public decimal? C183w6CalcRaw2 { get; set; }
        public decimal? C183w6RelativeRaw2 { get; set; }
        public decimal? C183w6SampleRaw2 { get; set; }
        public decimal? C184w3CalcRaw2 { get; set; }
        public decimal? C184w3RelativeRaw2 { get; set; }
        public decimal? C184w3SampleRaw2 { get; set; }
        public decimal? C200calcRaw2 { get; set; }
        public decimal? C200relativeRaw2 { get; set; }
        public decimal? C200sampleRaw2 { get; set; }
        public decimal? C201w7CalcRaw2 { get; set; }
        public decimal? C201w7RelativeRaw2 { get; set; }
        public decimal? C201w7SampleRaw2 { get; set; }
        public decimal? C201w9CalcRaw2 { get; set; }
        public decimal? C201w9RelativeRaw2 { get; set; }
        public decimal? C201w9SampleRaw2 { get; set; }
        public decimal? C202w6CalcRaw2 { get; set; }
        public decimal? C202w6RelativeRaw2 { get; set; }
        public decimal? C202w6SampleRaw2 { get; set; }
        public decimal? C203w3CalcRaw2 { get; set; }
        public decimal? C203w3RelativeRaw2 { get; set; }
        public decimal? C203w3SampleRaw2 { get; set; }
        public decimal? C203w6CalcRaw2 { get; set; }
        public decimal? C203w6RelativeRaw2 { get; set; }
        public decimal? C203w6SampleRaw2 { get; set; }
        public decimal? C204w3CalcRaw2 { get; set; }
        public decimal? C204w3RelativeRaw2 { get; set; }
        public decimal? C204w3SampleRaw2 { get; set; }
        public decimal? C204w6CalcRaw2 { get; set; }
        public decimal? C204w6RelativeRaw2 { get; set; }
        public decimal? C204w6SampleRaw2 { get; set; }
        public decimal? C205w3CalcRaw2 { get; set; }
        public decimal? C205w3RelativeRaw2 { get; set; }
        public decimal? C205w3SampleRaw2 { get; set; }
        public decimal? C215w3CalcRaw2 { get; set; }
        public decimal? C215w3RelativeRaw2 { get; set; }
        public decimal? C215w3SampleRaw2 { get; set; }
        public decimal? C220calcRaw2 { get; set; }
        public decimal? C220relativeRaw2 { get; set; }
        public decimal? C220sampleRaw2 { get; set; }
        public decimal? C221w9CalcRaw2 { get; set; }
        public decimal? C221w9RelativeRaw2 { get; set; }
        public decimal? C221w9SampleRaw2 { get; set; }
        public decimal? C225w3CalcRaw2 { get; set; }
        public decimal? C225w3RelativeRaw2 { get; set; }
        public decimal? C225w3SampleRaw2 { get; set; }
        public decimal? C225w6CalcRaw2 { get; set; }
        public decimal? C225w6RelativeRaw2 { get; set; }
        public decimal? C225w6SampleRaw2 { get; set; }
        public decimal? C226w3CalcRaw2 { get; set; }
        public decimal? C226w3RelativeRaw2 { get; set; }
        public decimal? C226w3SampleRaw2 { get; set; }
        public decimal? C60calcRaw2 { get; set; }
        public decimal? C60relativeRaw2 { get; set; }
        public decimal? C60sampleRaw2 { get; set; }
        public decimal? C80calcRaw2 { get; set; }
        public decimal? C80relativeRaw2 { get; set; }
        public decimal? C80sampleRaw2 { get; set; }
        public decimal? OtherCalcRaw2 { get; set; }
        public decimal? OtherRelativeRaw2 { get; set; }
        public decimal? OtherSampleRaw2 { get; set; }
        public decimal? C181calcRaw2 { get; set; }
        public decimal? C181relativeRaw2 { get; set; }
        public decimal? C181sampleRaw2 { get; set; }
        public decimal? C182calcRaw2 { get; set; }
        public decimal? C182relativeRaw2 { get; set; }
        public decimal? C182sampleRaw2 { get; set; }
        public decimal? C183calcRaw2 { get; set; }
        public decimal? C183relativeRaw2 { get; set; }
        public decimal? C183sampleRaw2 { get; set; }
        public decimal? C20111calcRaw2 { get; set; }
        public decimal? C20111relativeRaw2 { get; set; }
        public decimal? C20111sampleRaw2 { get; set; }
        public decimal? C2021114calcRaw2 { get; set; }
        public decimal? C2021114relativeRaw2 { get; set; }
        public decimal? C2021114sampleRaw2 { get; set; }
        public decimal? C221calcRaw2 { get; set; }
        public decimal? C221relativeRaw2 { get; set; }
        public decimal? C221sampleRaw2 { get; set; }
        public decimal? C240calcRaw2 { get; set; }
        public decimal? C240relativeRaw2 { get; set; }
        public decimal? C240sampleRaw2 { get; set; }
        public decimal? C241calcRaw2 { get; set; }
        public decimal? C241relativeRaw2 { get; set; }
        public decimal? C241sampleRaw2 { get; set; }
        public bool? C100userOverride { get; set; }
        public bool? C120userOverride { get; set; }
        public bool? C140userOverride { get; set; }
        public bool? C141userOverride { get; set; }
        public bool? C150userOverride { get; set; }
        public bool? C160userOverride { get; set; }
        public bool? C161userOverride { get; set; }
        public bool? C162userOverride { get; set; }
        public bool? C163userOverride { get; set; }
        public bool? C164userOverride { get; set; }
        public bool? C170userOverride { get; set; }
        public bool? C180userOverride { get; set; }
        public bool? C181w7UserOverride { get; set; }
        public bool? C181w9UserOverride { get; set; }
        public bool? C182w4UserOverride { get; set; }
        public bool? C182w6UserOverride { get; set; }
        public bool? C183w3UserOverride { get; set; }
        public bool? C183w6UserOverride { get; set; }
        public bool? C184w3UserOverride { get; set; }
        public bool? C200userOverride { get; set; }
        public bool? C201w7UserOverride { get; set; }
        public bool? C201w9UserOverride { get; set; }
        public bool? C202w6UserOverride { get; set; }
        public bool? C203w3UserOverride { get; set; }
        public bool? C203w6UserOverride { get; set; }
        public bool? C204w3UserOverride { get; set; }
        public bool? C204w6UserOverride { get; set; }
        public bool? C205w3UserOverride { get; set; }
        public bool? C215w3UserOverride { get; set; }
        public bool? C220userOverride { get; set; }
        public bool? C221w9UserOverride { get; set; }
        public bool? C225w3UserOverride { get; set; }
        public bool? C225w6UserOverride { get; set; }
        public bool? C226w3UserOverride { get; set; }
        public bool? C60userOverride { get; set; }
        public bool? C80userOverride { get; set; }
        public bool? OtherUserOverride { get; set; }
        public bool? C181userOverride { get; set; }
        public bool? C182userOverride { get; set; }
        public bool? C183userOverride { get; set; }
        public bool? C20111userOverride { get; set; }
        public bool? C2021114userOverride { get; set; }
        public bool? C221userOverride { get; set; }
        public bool? C240userOverride { get; set; }
        public bool? C241userOverride { get; set; }
        public decimal? C60FinalRelativeCalc { get; set; }
        public decimal? C80FinalRelativeCalc { get; set; }
        public decimal? C100FinalRelativeCalc { get; set; }
        public decimal? C120FinalRelativeCalc { get; set; }
        public decimal? C140FinalRelativeCalc { get; set; }
        public decimal? C141FinalRelativeCalc { get; set; }
        public decimal? C150FinalRelativeCalc { get; set; }
        public decimal? C160FinalRelativeCalc { get; set; }
        public decimal? C161FinalRelativeCalc { get; set; }
        public decimal? C162FinalRelativeCalc { get; set; }
        public decimal? C163FinalRelativeCalc { get; set; }
        public decimal? C164FinalRelativeCalc { get; set; }
        public decimal? C170FinalRelativeCalc { get; set; }
        public decimal? C180FinalRelativeCalc { get; set; }
        public decimal? C181w9FinalRelativeCalc { get; set; }
        public decimal? C181w7FinalRelativeCalc { get; set; }
        public decimal? C182w6FinalRelativeCalc { get; set; }
        public decimal? C182w4FinalRelativeCalc { get; set; }
        public decimal? C183w6FinalRelativeCalc { get; set; }
        public decimal? C183w3FinalRelativeCalc { get; set; }
        public decimal? C184w3FinalRelativeCalc { get; set; }
        public decimal? C200FinalRelativeCalc { get; set; }
        public decimal? C201w9FinalRelativeCalc { get; set; }
        public decimal? C201w7FinalRelativeCalc { get; set; }
        public decimal? C202w6FinalRelativeCalc { get; set; }
        public decimal? C203w6FinalRelativeCalc { get; set; }
        public decimal? C203w3FinalRelativeCalc { get; set; }
        public decimal? C204w6FinalRelativeCalc { get; set; }
        public decimal? C204w3FinalRelativeCalc { get; set; }
        public decimal? C205w3FinalRelativeCalc { get; set; }
        public decimal? C215w3FinalRelativeCalc { get; set; }
        public decimal? C220FinalRelativeCalc { get; set; }
        public decimal? C221w9FinalRelativeCalc { get; set; }
        public decimal? C225w6FinalRelativeCalc { get; set; }
        public decimal? C225w3FinalRelativeCalc { get; set; }
        public decimal? C226w3FinalRelativeCalc { get; set; }
        public decimal? OtherFinalRelativeCalc { get; set; }
        public decimal? C181FinalRelativeCalc { get; set; }
        public decimal? C182FinalRelativeCalc { get; set; }
        public decimal? C183FinalRelativeCalc { get; set; }
        public decimal? C22111FinalRelativeCalc { get; set; }
        public decimal? C2021114FinalRelativeCalc { get; set; }
        public decimal? C221FinalRelativeCalc { get; set; }
        public decimal? C240FinalRelativeCalc { get; set; }
        public decimal? C241FinalRelativeCalc { get; set; }
        public decimal? C60FinalSampleCalc { get; set; }
        public decimal? C80FinalSampleCalc { get; set; }
        public decimal? C100FinalSampleCalc { get; set; }
        public decimal? C120FinalSampleCalc { get; set; }
        public decimal? C140FinalSampleCalc { get; set; }
        public decimal? C141FinalSampleCalc { get; set; }
        public decimal? C150FinalSampleCalc { get; set; }
        public decimal? C160FinalSampleCalc { get; set; }
        public decimal? C161FinalSampleCalc { get; set; }
        public decimal? C162FinalSampleCalc { get; set; }
        public decimal? C163FinalSampleCalc { get; set; }
        public decimal? C164FinalSampleCalc { get; set; }
        public decimal? C170FinalSampleCalc { get; set; }
        public decimal? C180FinalSampleCalc { get; set; }
        public decimal? C181w9FinalSampleCalc { get; set; }
        public decimal? C181w7FinalSampleCalc { get; set; }
        public decimal? C182w6FinalSampleCalc { get; set; }
        public decimal? C182w4FinalSampleCalc { get; set; }
        public decimal? C183w6FinalSampleCalc { get; set; }
        public decimal? C183w3FinalSampleCalc { get; set; }
        public decimal? C184w3FinalSampleCalc { get; set; }
        public decimal? C200FinalSampleCalc { get; set; }
        public decimal? C201w9FinalSampleCalc { get; set; }
        public decimal? C201w7FinalSampleCalc { get; set; }
        public decimal? C202w6FinalSampleCalc { get; set; }
        public decimal? C203w6FinalSampleCalc { get; set; }
        public decimal? C203w3FinalSampleCalc { get; set; }
        public decimal? C204w6FinalSampleCalc { get; set; }
        public decimal? C204w3FinalSampleCalc { get; set; }
        public decimal? C205w3FinalSampleCalc { get; set; }
        public decimal? C215w3FinalSampleCalc { get; set; }
        public decimal? C220FinalSampleCalc { get; set; }
        public decimal? C221w9FinalSampleCalc { get; set; }
        public decimal? C225w6FinalSampleCalc { get; set; }
        public decimal? C225w3FinalSampleCalc { get; set; }
        public decimal? C226w3FinalSampleCalc { get; set; }
        public decimal? OtherFinalSampleCalc { get; set; }
        public decimal? C181FinalSampleCalc { get; set; }
        public decimal? C182FinalSampleCalc { get; set; }
        public decimal? C183FinalSampleCalc { get; set; }
        public decimal? C22111FinalSampleCalc { get; set; }
        public decimal? C2021114FinalSampleCalc { get; set; }
        public decimal? C221FinalSampleCalc { get; set; }
        public decimal? C240FinalSampleCalc { get; set; }
        public decimal? C241FinalSampleCalc { get; set; }
        public decimal? C171calcRaw1 { get; set; }
        public decimal? C171relativeRaw1 { get; set; }
        public decimal? C171sampleRaw1 { get; set; }
        public decimal? C171calcRaw2 { get; set; }
        public decimal? C171relativeRaw2 { get; set; }
        public decimal? C171sampleRaw2 { get; set; }
        public bool? C171userOverride { get; set; }
        public decimal? C171FinalRelativeCalc { get; set; }
        public decimal? C171FinalSampleCalc { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}
