using System;
using System.Collections.Generic;

namespace Foragelab.Core.DataModel
{
    public partial class NirdataMdistNdist
    {
        public long NirDataNmdistId { get; set; }
        public long NirDataId { get; set; }
        public decimal? Batch { get; set; }
        public decimal? Code { get; set; }
        public decimal? NDmResMDist { get; set; }
        public decimal? NDmResNDist { get; set; }
        public decimal? NCpMDist { get; set; }
        public decimal? NCpNDist { get; set; }
        public decimal? NSpMDist { get; set; }
        public decimal? NSpNDist { get; set; }
        public decimal? NAdicpMDist { get; set; }
        public decimal? NAdicpNDist { get; set; }
        public decimal? NNdicpMDist { get; set; }
        public decimal? NNdicpNDist { get; set; }
        public decimal? NNdicpnsMDist { get; set; }
        public decimal? NNdicpnsNDist { get; set; }
        public decimal? NNh3cpeMDist { get; set; }
        public decimal? NNh3cpeNDist { get; set; }
        public decimal? NAceticMDist { get; set; }
        public decimal? NAceticNDist { get; set; }
        public decimal? NPropionicMDist { get; set; }
        public decimal? NPropionicNDist { get; set; }
        public decimal? NButyricMDist { get; set; }
        public decimal? NButyricNDist { get; set; }
        public decimal? NLacticMDist { get; set; }
        public decimal? NLacticNDist { get; set; }
        public decimal? NIsoButyricMDist { get; set; }
        public decimal? NIsoButyricNDist { get; set; }
        public decimal? NTotVfaMDist { get; set; }
        public decimal? NTotVfaNDist { get; set; }
        public decimal? NTitAcMDist { get; set; }
        public decimal? NTitAcNDist { get; set; }
        public decimal? NSugarMDist { get; set; }
        public decimal? NSugarNDist { get; set; }
        public decimal? NStarchMDist { get; set; }
        public decimal? NStarchNDist { get; set; }
        public decimal? NStarchEaMDist { get; set; }
        public decimal? NStarchEaNDist { get; set; }
        public decimal? NSolFiberMDist { get; set; }
        public decimal? NSolFiberNDist { get; set; }
        public decimal? NAdfMDist { get; set; }
        public decimal? NAdfNDist { get; set; }
        public decimal? NANdfMDist { get; set; }
        public decimal? NANdfNDist { get; set; }
        public decimal? NCfMDist { get; set; }
        public decimal? NCfNDist { get; set; }
        public decimal? NLigninMDist { get; set; }
        public decimal? NLigninNDist { get; set; }
        public decimal? NNdfdIv12MDist { get; set; }
        public decimal? NNdfdIv12NDist { get; set; }
        public decimal? NNdfdIv24MDist { get; set; }
        public decimal? NNdfdIv24NDist { get; set; }
        public decimal? NNdfdIv30MDist { get; set; }
        public decimal? NNdfdIv30NDist { get; set; }
        public decimal? NNdfdIv48MDist { get; set; }
        public decimal? NNdfdIv48NDist { get; set; }
        public decimal? NNdfdIv240MDist { get; set; }
        public decimal? NNdfdIv240NDist { get; set; }
        public decimal? NINdfMDist { get; set; }
        public decimal? NINdfNDist { get; set; }
        public decimal? NDmd2MDist { get; set; }
        public decimal? NDmd2NDist { get; set; }
        public decimal? NNutrecoPdMDist { get; set; }
        public decimal? NNutrecoPdNDist { get; set; }
        public decimal? NNutrecoIfMDist { get; set; }
        public decimal? NNutrecoIfNDist { get; set; }
        public decimal? NIvsd72MDist { get; set; }
        public decimal? NIvsd72NDist { get; set; }
        public decimal? NIvsd74MDist { get; set; }
        public decimal? NIvsd74NDist { get; set; }
        public decimal? NFatEeMDist { get; set; }
        public decimal? NFatEeNDist { get; set; }
        public decimal? NTfaMDist { get; set; }
        public decimal? NTfaNDist { get; set; }
        public decimal? NAshMDist { get; set; }
        public decimal? NAshNDist { get; set; }
        public decimal? NCaMDist { get; set; }
        public decimal? NCaNDist { get; set; }
        public decimal? NPMDist { get; set; }
        public decimal? NPNDist { get; set; }
        public decimal? NMgMDist { get; set; }
        public decimal? NMgNDist { get; set; }
        public decimal? NKMDist { get; set; }
        public decimal? NKNDist { get; set; }
        public decimal? NSMDist { get; set; }
        public decimal? NSNDist { get; set; }
        public decimal? NNaMDist { get; set; }
        public decimal? NNaNDist { get; set; }
        public decimal? NClMDist { get; set; }
        public decimal? NClNDist { get; set; }
        public decimal? NFeMDist { get; set; }
        public decimal? NFeNDist { get; set; }
        public decimal? NPHMDist { get; set; }
        public decimal? NPHNDist { get; set; }
        public decimal? NNitrateMDist { get; set; }
        public decimal? NNitrateNDist { get; set; }
        public decimal? NC12MDist { get; set; }
        public decimal? NC12NDist { get; set; }
        public decimal? NC16MDist { get; set; }
        public decimal? NC16NDist { get; set; }
        public decimal? NC18MDist { get; set; }
        public decimal? NC18NDist { get; set; }
        public decimal? NC181MDist { get; set; }
        public decimal? NC181NDist { get; set; }
        public decimal? NC182MDist { get; set; }
        public decimal? NC182NDist { get; set; }
        public decimal? NC183MDist { get; set; }
        public decimal? NC183NDist { get; set; }
        public decimal? NC130MDist { get; set; }
        public decimal? NC130NDist { get; set; }
        public decimal? NC140MDist { get; set; }
        public decimal? NC140NDist { get; set; }
        public decimal? NC161MDist { get; set; }
        public decimal? NC161NDist { get; set; }
        public decimal? NC170MDist { get; set; }
        public decimal? NC170NDist { get; set; }
        public decimal? NC200MDist { get; set; }
        public decimal? NC200NDist { get; set; }
        public decimal? NC220MDist { get; set; }
        public decimal? NC220NDist { get; set; }
        public decimal? NVtoxMDist { get; set; }
        public decimal? NVtoxNDist { get; set; }
        public decimal? NTdonMDist { get; set; }
        public decimal? NTdonNDist { get; set; }
        public decimal? NNdfomMDist { get; set; }
        public decimal? NNdfomNDist { get; set; }
        public decimal? NNdfomRMDist { get; set; }
        public decimal? NNdfomRNDist { get; set; }
        public decimal? NDpMDist { get; set; }
        public decimal? NDpNDist { get; set; }
        public decimal? NStrepGMDist { get; set; }
        public decimal? NStrepGNDist { get; set; }
        public decimal? NUnsatFatMDist { get; set; }
        public decimal? NUnsatFatNDist { get; set; }
        public decimal? NSatFatMDist { get; set; }
        public decimal? NSatFatNDist { get; set; }
        public decimal? NPrMDist { get; set; }
        public decimal? NPrNDist { get; set; }
        public decimal? NNdrMDist { get; set; }
        public decimal? NNdrNDist { get; set; }
        public decimal? NPlMDist { get; set; }
        public decimal? NPlNDist { get; set; }
        public decimal? GhMDist { get; set; }
        public decimal? GhNDist { get; set; }
    }
}
