using System;
using System.Collections.Generic;

namespace Foragelab.Core.DataModel
{
    public partial class SmSamples
    {
        public decimal Code { get; set; }
        public decimal Batch { get; set; }
        public long Sampleid { get; set; }
        public bool? Alldone { get; set; }
        public bool? Release { get; set; }
        public bool? Paid { get; set; }
        public DateTime? Arrival { get; set; }
        public DateTime? Return { get; set; }
        public decimal? Receipt { get; set; }
        public decimal? Postage { get; set; }
        public string Account { get; set; }
        public string FarmId { get; set; }
        public string Farmname { get; set; }
        public bool? CopyTo { get; set; }
        public string Name { get; set; }
        public string Name1 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Citystzip { get; set; }
        public string Describe { get; set; }
        public string Energy { get; set; }
        public string FeedType { get; set; }
        public bool? Wet { get; set; }
        public decimal? Cutting { get; set; }
        public decimal? Hfee { get; set; }
        public DateTime? Sampled { get; set; }
        public decimal? Ctfee { get; set; }
        public string Comments { get; set; }
        public bool? Billto { get; set; }
        public string BillCode { get; set; }
        public decimal? Ph { get; set; }
        public decimal? DmPan { get; set; }
        public decimal? DmPansm { get; set; }
        public decimal? DmDry { get; set; }
        public decimal? Dm2Pan { get; set; }
        public decimal? Dm2Pansm { get; set; }
        public decimal? Dm2Dry { get; set; }
        public decimal? HdmPan { get; set; }
        public decimal? HdmPansm { get; set; }
        public decimal? HdmDry { get; set; }
        public decimal? Ps1 { get; set; }
        public decimal? Ps2 { get; set; }
        public decimal? Ps3 { get; set; }
        public decimal? Ndinwt { get; set; }
        public decimal? LacWt { get; set; }
        public decimal? AdfBag { get; set; }
        public decimal? AdfBagtr { get; set; }
        public decimal? AdfBagsm { get; set; }
        public decimal? Adf2Bag { get; set; }
        public decimal? Adf2Bagtr { get; set; }
        public decimal? Adf2Bagsm { get; set; }
        public decimal? NdfBag { get; set; }
        public decimal? NdfBagtr { get; set; }
        public decimal? NdfBagsm { get; set; }
        public decimal? Ndf2Bag { get; set; }
        public decimal? Ndf2Bagtr { get; set; }
        public decimal? Ndf2Bagsm { get; set; }
        public decimal? LigSm { get; set; }
        public decimal? LigCrusm { get; set; }
        public decimal? LigCruash { get; set; }
        public decimal? Lig2Sm { get; set; }
        public decimal? Lig2Crusm { get; set; }
        public decimal? Lig2Cruas { get; set; }
        public decimal? AshCru { get; set; }
        public decimal? AshSm { get; set; }
        public decimal? AshCrusm { get; set; }
        public decimal? FatCru { get; set; }
        public decimal? FatSm { get; set; }
        public decimal? FatCrusm { get; set; }
        public decimal? Pro1Sm { get; set; }
        public decimal? Pro1Pc { get; set; }
        public decimal? StrchBl { get; set; }
        public decimal? StrchPc { get; set; }
        public decimal? StrchWt { get; set; }
        public decimal? StrchPc2 { get; set; }
        public decimal? StrchWt2 { get; set; }
        public decimal? Pro3Sm { get; set; }
        public decimal? Pro3Pc { get; set; }
        public decimal? SproBagsm { get; set; }
        public decimal? SproBag { get; set; }
        public decimal? SproPc { get; set; }
        public decimal? SproSm { get; set; }
        public decimal? SproBgsmd { get; set; }
        public decimal? Spr2Bagsm { get; set; }
        public decimal? Spr2Bag { get; set; }
        public decimal? Spr2Pc { get; set; }
        public decimal? Spr2Sm { get; set; }
        public decimal? Spr2Bgsmd { get; set; }
        public decimal? AdfproSm { get; set; }
        public decimal? AdfPc { get; set; }
        public decimal? AdfPcsm { get; set; }
        public decimal? NdfproSm { get; set; }
        public decimal? NdfPc { get; set; }
        public decimal? AmmoniaSm { get; set; }
        public decimal? AmmoniaPc { get; set; }
        public decimal? NpnSm { get; set; }
        public decimal? NpnPc { get; set; }
        public decimal? UipSm { get; set; }
        public decimal? UipPc { get; set; }
        public decimal? No3Sm { get; set; }
        public decimal? No3Pc { get; set; }
        public decimal? ClSm { get; set; }
        public decimal? ClPc { get; set; }
        public decimal? SSm { get; set; }
        public decimal? SFl { get; set; }
        public decimal? SFlpr { get; set; }
        public decimal? NaclSm { get; set; }
        public decimal? NaclTt { get; set; }
        public bool? Lmold { get; set; }
        public decimal? MoD1 { get; set; }
        public decimal? MoD2 { get; set; }
        public decimal? MoP1 { get; set; }
        public decimal? MoP2 { get; set; }
        public decimal? MoD3 { get; set; }
        public decimal? MoP3 { get; set; }
        public decimal? MoD4 { get; set; }
        public decimal? MoP4 { get; set; }
        public decimal? Mold { get; set; }
        public decimal? Yeast { get; set; }
        public decimal? Zeral { get; set; }
        public decimal? Don { get; set; }
        public decimal? T2 { get; set; }
        public decimal? Aflat { get; set; }
        public decimal? MinSm { get; set; }
        public decimal? Mdwt { get; set; }
        public decimal? Ca { get; set; }
        public decimal? Pho { get; set; }
        public decimal? Mg { get; set; }
        public decimal? K { get; set; }
        public decimal? Na { get; set; }
        public decimal? Fe { get; set; }
        public decimal? Mn { get; set; }
        public decimal? Zn { get; set; }
        public decimal? Cu { get; set; }
        public decimal? ValAflat { get; set; }
        public decimal? ValDon { get; set; }
        public bool? Lmoisture { get; set; }
        public bool? Lprotein { get; set; }
        public bool? Ladin { get; set; }
        public bool? Lndf { get; set; }
        public bool? Lndfs { get; set; }
        public bool? Lndf30 { get; set; }
        public bool? Llignin { get; set; }
        public bool? Lfat { get; set; }
        public bool? Lno3 { get; set; }
        public bool? Lnpn { get; set; }
        public bool? Lsolpro { get; set; }
        public bool? Luip { get; set; }
        public bool? Lpepsin { get; set; }
        public bool? Lsulfur { get; set; }
        public bool? Lchloride { get; set; }
        public bool? Ltrace { get; set; }
        public bool? Lsalt { get; set; }
        public bool? Lash { get; set; }
        public bool? Ltoxin { get; set; }
        public bool? Lammonia { get; set; }
        public bool? Lfa { get; set; }
        public bool? Lsize { get; set; }
        public bool? Losu { get; set; }
        public bool? Lurease { get; set; }
        public bool? Ltitrate { get; set; }
        public decimal? Class { get; set; }
        public bool? Special { get; set; }
        public decimal? Due { get; set; }
        public DateTime? Billed { get; set; }
        public string Reckcode { get; set; }
        public decimal? Invoiceno { get; set; }
        public bool? Llact { get; set; }
        public bool? Lstarch { get; set; }
        public bool? Lsugar { get; set; }
        public bool? Tempbool { get; set; }
        public string Idcode { get; set; }
        public bool? Lndin { get; set; }
        public bool? Lrbean { get; set; }
        public bool? Linvndf { get; set; }
        public bool? Laflat { get; set; }
        public bool? Lzeral { get; set; }
        public bool? Ldon { get; set; }
        public bool? Lt2 { get; set; }
        public bool? Lcap { get; set; }
        public bool? Lmacro { get; set; }
        public bool? Ladf { get; set; }
        public bool? Lcfiber { get; set; }
        public decimal? Ht2 { get; set; }
        public decimal? Das { get; set; }
        public decimal? Neo { get; set; }
        public bool? Lht2 { get; set; }
        public bool? Ldas { get; set; }
        public bool? Lneo { get; set; }
        public decimal? LigAdf { get; set; }
        public decimal? Wewt { get; set; }
        public decimal? KernelH { get; set; }
        public bool? Lbq { get; set; }
        public bool? Switch { get; set; }
        public bool? Lnir { get; set; }
        public decimal? Nir { get; set; }
        public bool? Ldrycow { get; set; }
        public bool? Lcornell { get; set; }
        public decimal? Hrvtyr { get; set; }
        public bool? Lbyprod { get; set; }
        public decimal? Pro2Sm { get; set; }
        public decimal? Pro2Pc { get; set; }
        public decimal? GlucWt { get; set; }
        public decimal? GlucPc { get; set; }
        public decimal? WetSilage { get; set; }
        public decimal? NaOh { get; set; }
        public decimal? Lactic { get; set; }
        public decimal? WsSugar { get; set; }
        public decimal? Ethanol { get; set; }
        public decimal? RumenBuf { get; set; }
        public decimal? LacticMl { get; set; }
        public decimal? VfaMl { get; set; }
        public decimal? Acetic { get; set; }
        public decimal? Proprionic { get; set; }
        public decimal? Isobutyric { get; set; }
        public decimal? Butyric { get; set; }
        public decimal? NCp { get; set; }
        public decimal? NAdf { get; set; }
        public decimal? NNdf { get; set; }
        public decimal? NHdP { get; set; }
        public decimal? NIsP { get; set; }
        public decimal? NCa { get; set; }
        public decimal? NP { get; set; }
        public decimal? NMg { get; set; }
        public decimal? NK { get; set; }
        public decimal? NHyg { get; set; }
        public decimal? NLig { get; set; }
        public decimal? NSta { get; set; }
        public decimal? NFat { get; set; }
        public decimal? NAsh { get; set; }
        public bool? LAsh { get; set; }
        public bool? LFat { get; set; }
        public bool? LSta { get; set; }
        public bool? LLig { get; set; }
        public bool? LHyg { get; set; }
        public bool? LK { get; set; }
        public bool? LMg { get; set; }
        public bool? LP { get; set; }
        public bool? LCa { get; set; }
        public bool? LIsP { get; set; }
        public bool? LHdP { get; set; }
        public bool? LNdf { get; set; }
        public bool? LAdf { get; set; }
        public bool? LCp { get; set; }
        public bool? LNStarch { get; set; }
        public bool? Lcho { get; set; }
        public decimal? Ndawt { get; set; }
        public decimal? Ndacruc { get; set; }
        public decimal? Ndacrucf { get; set; }
        public decimal? Ndafilt { get; set; }
        public decimal? Tvfa { get; set; }
        public bool? Lselenium { get; set; }
        public decimal? Agclass { get; set; }
        public DateTime? Process { get; set; }
        public string Codeset { get; set; }
    }
}
